[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@11.15.1 --activate",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build"
]
